Internal Server Error: /api/v1/suppliers/
Traceback (most recent call last):
  File "C:\Users\diar8\OneDrive\Рабочий стол\Coding\resmart_duken\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\diar8\OneDrive\Рабочий стол\Coding\resmart_duken\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\diar8\OneDrive\Рабочий стол\Coding\resmart_duken\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\diar8\OneDrive\Рабочий стол\Coding\resmart_duken\venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\diar8\OneDrive\Рабочий стол\Coding\resmart_duken\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\diar8\OneDrive\Рабочий стол\Coding\resmart_duken\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\diar8\OneDrive\Рабочий стол\Coding\resmart_duken\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\diar8\OneDrive\Рабочий стол\Coding\resmart_duken\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\diar8\OneDrive\Рабочий стол\Coding\resmart_duken\venv\Lib\site-packages\rest_framework\mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
                                    ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\diar8\OneDrive\Рабочий стол\Coding\resmart_duken\backend\app\views.py", line 29, in get_queryset
    return self.queryset.filter(id__in=[dto.id for dto in suppliers_dto])
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable
"GET /api/v1/suppliers/?q=3&page=1&page_size=25 HTTP/1.1" 500 105478
Internal Server Error: /api/v1/suppliers/
Traceback (most recent call last):
  File "C:\Users\diar8\OneDrive\Рабочий стол\Coding\resmart_duken\venv\Lib\site-packages\django_redis\cache.py", line 29, in _decorator
    return method(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\diar8\OneDrive\Рабочий стол\Coding\resmart_duken\venv\Lib\site-packages\django_redis\cache.py", line 99, in _get
    return self.client.get(key, default=default, version=version, client=client)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\diar8\OneDrive\Рабочий стол\Coding\resmart_duken\venv\Lib\site-packages\django_redis\client\default.py", line 260, in get
    raise ConnectionInterrupted(connection=client) from e
django_redis.exceptions.ConnectionInterrupted: Redis ConnectionError: Error 10061 connecting to 127.0.0.1:6379. Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\diar8\OneDrive\Рабочий стол\Coding\resmart_duken\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\diar8\OneDrive\Рабочий стол\Coding\resmart_duken\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\diar8\OneDrive\Рабочий стол\Coding\resmart_duken\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\diar8\OneDrive\Рабочий стол\Coding\resmart_duken\venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\diar8\OneDrive\Рабочий стол\Coding\resmart_duken\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\diar8\OneDrive\Рабочий стол\Coding\resmart_duken\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\diar8\OneDrive\Рабочий стол\Coding\resmart_duken\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\diar8\OneDrive\Рабочий стол\Coding\resmart_duken\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\diar8\OneDrive\Рабочий стол\Coding\resmart_duken\venv\Lib\site-packages\rest_framework\mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
                                    ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\diar8\OneDrive\Рабочий стол\Coding\resmart_duken\backend\app\views.py", line 27, in get_queryset
    suppliers_dto = self.service_layer.search(q)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\diar8\OneDrive\Рабочий стол\Coding\resmart_duken\backend\app\services\supplier.py", line 12, in search
    search_result = self.dao.search(query)
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\diar8\OneDrive\Рабочий стол\Coding\resmart_duken\backend\app\daos\supplier_dao.py", line 9, in search
    queryset = cache.get_or_set(
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\diar8\OneDrive\Рабочий стол\Coding\resmart_duken\venv\Lib\site-packages\django\core\cache\backends\base.py", line 227, in get_or_set
    val = self.get(key, self._missing_key, version=version)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\diar8\OneDrive\Рабочий стол\Coding\resmart_duken\venv\Lib\site-packages\django_redis\cache.py", line 92, in get
    value = self._get(key, default, version, client)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\diar8\OneDrive\Рабочий стол\Coding\resmart_duken\venv\Lib\site-packages\django_redis\cache.py", line 36, in _decorator
    raise e.__cause__
  File "C:\Users\diar8\OneDrive\Рабочий стол\Coding\resmart_duken\venv\Lib\site-packages\django_redis\client\default.py", line 258, in get
    value = client.get(key)
            ^^^^^^^^^^^^^^^
  File "C:\Users\diar8\OneDrive\Рабочий стол\Coding\resmart_duken\venv\Lib\site-packages\redis\commands\core.py", line 1829, in get
    return self.execute_command("GET", name, keys=[name])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\diar8\OneDrive\Рабочий стол\Coding\resmart_duken\venv\Lib\site-packages\redis\client.py", line 622, in execute_command
    return self._execute_command(*args, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\diar8\OneDrive\Рабочий стол\Coding\resmart_duken\venv\Lib\site-packages\redis\client.py", line 628, in _execute_command
    conn = self.connection or pool.get_connection()
                              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\diar8\OneDrive\Рабочий стол\Coding\resmart_duken\venv\Lib\site-packages\redis\utils.py", line 188, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\diar8\OneDrive\Рабочий стол\Coding\resmart_duken\venv\Lib\site-packages\redis\connection.py", line 1522, in get_connection
    connection.connect()
  File "C:\Users\diar8\OneDrive\Рабочий стол\Coding\resmart_duken\venv\Lib\site-packages\redis\connection.py", line 379, in connect
    self.connect_check_health(check_health=True)
  File "C:\Users\diar8\OneDrive\Рабочий стол\Coding\resmart_duken\venv\Lib\site-packages\redis\connection.py", line 391, in connect_check_health
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 10061 connecting to 127.0.0.1:6379. Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение.
"GET /api/v1/suppliers/?page=1&page_size=25 HTTP/1.1" 500 175826
Internal Server Error: /api/v1/supplies/
Traceback (most recent call last):
  File "C:\Users\diar8\OneDrive\Рабочий стол\Coding\resmart_duken\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\diar8\OneDrive\Рабочий стол\Coding\resmart_duken\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\diar8\OneDrive\Рабочий стол\Coding\resmart_duken\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\diar8\OneDrive\Рабочий стол\Coding\resmart_duken\venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\diar8\OneDrive\Рабочий стол\Coding\resmart_duken\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\diar8\OneDrive\Рабочий стол\Coding\resmart_duken\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\diar8\OneDrive\Рабочий стол\Coding\resmart_duken\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\diar8\OneDrive\Рабочий стол\Coding\resmart_duken\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\diar8\OneDrive\Рабочий стол\Coding\resmart_duken\venv\Lib\site-packages\rest_framework\mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
                                    ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\diar8\OneDrive\Рабочий стол\Coding\resmart_duken\backend\app\views.py", line 38, in get_queryset
    return self.queryset.filter(id__in=[dto.id for dto in supplies_dto])
           ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'filter'
"GET /api/v1/supplies/ HTTP/1.1" 500 103578
Internal Server Error: /api/v1/suppliers/
Traceback (most recent call last):
  File "C:\Users\diar8\OneDrive\Рабочий стол\Coding\resmart_duken\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\diar8\OneDrive\Рабочий стол\Coding\resmart_duken\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\diar8\OneDrive\Рабочий стол\Coding\resmart_duken\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\diar8\OneDrive\Рабочий стол\Coding\resmart_duken\venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\diar8\OneDrive\Рабочий стол\Coding\resmart_duken\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\diar8\OneDrive\Рабочий стол\Coding\resmart_duken\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\diar8\OneDrive\Рабочий стол\Coding\resmart_duken\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\diar8\OneDrive\Рабочий стол\Coding\resmart_duken\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\diar8\OneDrive\Рабочий стол\Coding\resmart_duken\venv\Lib\site-packages\rest_framework\mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
                                    ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\diar8\OneDrive\Рабочий стол\Coding\resmart_duken\backend\app\views.py", line 27, in get_queryset
    return self.queryset.filter(id__in=[dto.id for dto in suppliers_dto])
           ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'filter'
"GET /api/v1/suppliers/?page=1&page_size=25 HTTP/1.1" 500 108020
Internal Server Error: /api/v1/suppliers/
Traceback (most recent call last):
  File "C:\Users\diar8\OneDrive\Рабочий стол\Coding\resmart_duken\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\diar8\OneDrive\Рабочий стол\Coding\resmart_duken\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\diar8\OneDrive\Рабочий стол\Coding\resmart_duken\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\diar8\OneDrive\Рабочий стол\Coding\resmart_duken\venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\diar8\OneDrive\Рабочий стол\Coding\resmart_duken\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\diar8\OneDrive\Рабочий стол\Coding\resmart_duken\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\diar8\OneDrive\Рабочий стол\Coding\resmart_duken\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\diar8\OneDrive\Рабочий стол\Coding\resmart_duken\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\diar8\OneDrive\Рабочий стол\Coding\resmart_duken\venv\Lib\site-packages\rest_framework\mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
                                    ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\diar8\OneDrive\Рабочий стол\Coding\resmart_duken\backend\app\views.py", line 27, in get_queryset
    return self.queryset.filter(id__in=[dto.id for dto in suppliers_dto])
           ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'filter'
"GET /api/v1/suppliers/?page=1&page_size=25 HTTP/1.1" 500 107925
